source "http://rubygems.org"

gem 'sinatra'
gem 'mongoid'
gem 'sinatra-contrib'
gem 'titleize'
gem 'chronic'
gem 'street_address_ext'

group :test, :development do
  gem 'rr'
  gem 'timecop'
  gem 'guard'
  gem 'guard-minitest'
  gem 'minitest'
end

